# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty

# Server
# source:           docs
destination:      _gh_pages
# host:             127.0.0.1

#host:             0.0.0.0
#port:             4001

baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "http://fobia.github.io" # the base hostname & protocol for your site
lang: "ru"
twitter_username: TyurinD
github_username:  tyurind

# color-scheme: "#007bff" # the scheme can be any HEX code like "#00aa55"
color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"


encoding:         UTF-8


# Site settings
title: Мой личный блог
email: fobia3d@mail.ru
description: > # this means to ignore newlines until "baseurl:"
  Тут только мои заметки, для личных нужд.

paginate: 10 # increase this value to reflect how many posts per page you want
paginate_path: "/page:num/"
  
sass:
  sass_dir: /assets/css/_sass
#  style: compressed


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate

header_pages:
  - _pages/blog.md
  - _pages/about.md
  - _pages/contact.md
  - _pages/setup.md
  - _pages/github.md

minima:
  date_format: " %-d %b, %Y"
  social_links:
    twitter: TyurinD
    github: tyurind
    telegram: fobia3d


google_analytics: UA-NNNNNNNN-N

collections:
  notes:
    output: true
    permalink: /notes/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - _notes
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp