# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
# source:           docs
destination:      _gh_pages
# host:             127.0.0.1

#host:             0.0.0.0
#port:             4001

baseurl: "/myblog" # the subpath of your site, e.g. /blog
url: "http://fobia.github.io" # the base hostname & protocol for your site

encoding:         UTF-8


# Site settings
title: Your awesome title
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.




# Build settings
theme: minima
plugins:
  - jekyll-feed

#

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

